### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by FunnyDevs** [jug6ernaut/DataBindingAdapter#1]
I have tried your sample app and it doesn't work. No error in logcat, but the activity is empty

**Comment by williamwebb** [comment]
Sorry about that, needed to update the documentation & few parts of the code. Specifically the layout for the row items and adding a LayoutManager to to recyclerview.

`app:layoutManager="@{LayoutManagers.linear()}"`

No update the the library is necessary. Changes have been committed. Let me know if you have any further issues.

**Comment by FunnyDevs** [comment]
Ok, thanks, now i works! 
Is possibile handle different row layouts for recyclerview???

**Comment by williamwebb** [comment]
Currently no. Though it is an interesting proposition... Submit another issue for this feature as an enhancement & ill get to looking into it :).
